artifact_path: artifacts
caikit_nlp_version: 0.2.2.dev111+g6ad04d9
created: '2023-10-18 14:09:27.203087'
eos_token: </s>
module_class: caikit_nlp.modules.text_generation.text_generation_local.TextGeneration
module_id: f9181353-4ccf-4572-bd1e-f12bcda26792
name: Text Generation
saved: '2023-10-18 14:09:27.203098'
torch_dtype: torch.float32
tracking_id: 1a01d021-8303-4831-b44c-08567270de2d
training_logs: training_logs.jsonl
version: 0.1.0
